org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# 强制清理KSP缓存
ksp.use.gradle.cache.location=false
ksp.incremental=false
org.gradle.gradle.kotlin.compile.kotlinc.use.classpath.cache=false