#!/bin/sh

#
# Copyright © 2015-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       1. Gradle tasks that don't need a daemon
#       2. Gradle tasks in a Gradle installation that doesn't support the Gradle wrapper script
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need to convert to absolute path
app_path=$(cd "$(dirname "$app_path")"; pwd)
app_home="$app_path"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    warn "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false

case "`uname`" in
  CYGWIN*)
    cygwin=true
    ;;
  Darwin*)
    darwin=true
    ;;
  MSYS*|MINGW*)
    msys=true
    nonstop=true
    ;;
esac

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments (kludge to limit the number of sh -c executions)
    for arg do
        if
            case $arg in                                #   skip
                -*)   ;;                               #   native unix option
                /=*)  ;;                               #   native env var or path
                *)    ;;                               #   java class
            esac
        then
            # Convert git-bash style paths to windows
            # Handles multiple patterns: //path/to/file and /path/to\\file
            if [[ $arg =~ ^/.* ]]; then
                arg=$(cygpath --path --ignore --mixed "$arg")
            fi
            # Convert git-bash style paths to windows
            if [[ $arg =~ ^/.* ]]; then
                arg=$(cygpath --path --ignore --mixed "$arg")
            fi
        fi
        shift
    done
fi

# For MSYS, convert paths to Windows format before running java
if $msys ; then
    APP_HOME=$(convert_path -m "$APP_HOME")
    CLASSPATH=$(convert_path -m "$CLASSPATH")
    JAVACMD=$(convert_path -m "$JAVACMD")

    # Now convert the arguments (kludge to limit the number of sh -c executions)
    for arg do
        if
            case $arg in                                #   skip
                -*)   ;;                               #   native unix option
                /=*)  ;;                               #   native env var or path
                *)    ;;                               #   java class
            esac
        then
            # Convert git-bash style paths to windows
            if [[ $arg =~ ^/.* ]]; then
                arg=$(convert_path -m "$arg")
            fi
            # Convert git-bash style paths to windows
            if [[ $arg =~ ^/.* ]]; then
                arg=$(convert_path -m "$arg")
            fi
        fi
        shift
    done
fi

# For Darwin, use options from https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/cross_development/Running%20Shell%20Scripts%20in%20Cross-Platform%20Projects/#!/bin/sh

if $darwin; then
    GRADLE_OPTS=$(line="$GRADLE_OPTS" awk 'sub(/^$/", "-Dorg.gradle.appname='$0'") /'; export GRADLE_OPTS
    # Determine the minimum Java version
    javaVersionInfo=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f 1)
    # Check Java version
    if [[ $javaVersionInfo -lt 17 ]]; then
        echo "ERROR: Gradle requires Java 17 or later. Current version: $javaVersionInfo"
        exit 1
    fi
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g"; done
    saveIFS=$IFS
    IFS=' '
    echo "$*"
}

# Apply escapes to args
eval set -- $(save "$@") APP_HOME="$(cd "$(dirname "$app_path")"; pwd)" CLASSPATH="$CLASSPATH"

# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
function splitJvmOpts() {
    JVM_OPTS=($@)
}

function splitGradleOpts() {
    GRADLE_OPTS=($@)
}

# Collect all arguments for the java command, following the shell quoting and substitution rules
function collectAllArguments() {
    while IFS= read -r passArg || [[ -n "$passArg" ]]; do
        if [[ "$passArg" =~ ^-D.*=.*$ ]]; then
            # Remove -D prefix, split by =, add --JVM arg, add to $JVM_OPTS array, and continue
            splitJvmOpts "${passArg:2}"
        else
            "$JVM_OPTS[@]" "$passArg"
        fi
    done

    # echo "${JVM_OPTS[@]}"
    # echo "$@"

    while [[ $# -gt 0 ]] && [[ "$1" == *=* ]]; do
      "$JVM_OPTS[@]" "$1"
      shift
    done

    while [[ $# -gt 0 ]]; do
        eval collectAllArguments "$@"
        shift
    done

    "$JVM_OPTS[@]"
}

# Add a JVM property to call when running Gradle (used by Gradle when running the wrapper to check for updates)
jvmPropertiesList="-Dorg.gradle.wrapper.version=https://services.gradle.org/distributions/gradle-8.9-bin.zip"

# Collect all arguments for the java command
eval set -- $(splitJvmOpts $jvmPropertiesList "$@" --jvm-output-file build/globals.txt "$@"

# Execute the Gradle command with the collected arguments
exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
